export const types = {

  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FILED: 'AUTH_FILED',

  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FILED: 'UPDATE_USER_FILED',

  GET_PRODUCTS_START: 'GET_PRODUCTS_START',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FILED: 'GET_PRODUCTS_FILED',

  GET_ORDER_START: 'GET_ORDER_START',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_FILED: 'GET_ORDER_FILED',

  ON_SELECT_PRODUCT: 'ON_SELECT_PRODUCT',

  ADD_TO_CART: 'ADD_TO_CART',

  REMOVE_CART_DATA: 'REMOVE_CART_DATA',

  GET_FAVORITE_PRODUCTS_OF_USER_START: 'GET_FAVORITE_PRODUCTS_OF_USER_START',
  GET_FAVORITE_PRODUCTS_OF_USER_SUCCESS: 'GET_FAVORITE_PRODUCTS_OF_USER_SUCCESS',
  GET_FAVORITE_PRODUCTS_OF_USER_FILED: 'GET_FAVORITE_PRODUCTS_OF_USER_FILED',

  SING_OUT: 'SING_OUT',
};









